### ISSUE TITLE
Port to Xamarin Android (Mono for Android)

### ISSUE THREAD

**Issue by JesseChang** [ericharlow/TICEWidgets#2]
Hi Eric, 

I have a great inspiration from your project and want to port your project to Xamarin Android. I'm asking if you don't mind, may I put my project on github (of course I will indicate the origin project and idea is from you)? 

Please let me know

Thanks!
(Sorry for contacting via Issue, I can't find other way to contact you)

Jesse

**Comment by ericharlow** [comment]
sure use my project. I really appreciate you giving me attribution. I would suggest putting a link in your README.md file on your github project to my project.
